version: '3.1'

services:
  web:
    build: ./odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./odoo/odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: odoo -c /etc/odoo/odoo.conf

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-odoo}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-odoo}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
